const api = p => fetch('/api' + p).then(r => { if(!r.ok) throw new Error(r.statusText); return r.json(); });
const app = document.getElementById('app');
const esc = s => (s ?? '').toString().replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function pageCard(p){ return `<article class="card"><h3><a href="/elearn/${p.id}">${esc(p.title)}</a></h3><p class="muted">${esc(p.breadcrumb||p.category||'')}</p><p>${esc((p.content_text||'').slice(0,260))}...</p><a href="${esc(p.source_url)}" target="_blank">Source</a></article>`; }
async function home(){ app.innerHTML=`<section class="card"><h1>Fiat Multipla eLearn crawler, search & components</h1><p>Phase 2A proof-of-concept for source capture, PostgreSQL storage, Meilisearch indexing, and component pages.</p><p><a href="/search">Search imported pages</a> · <a href="/components">Browse components</a></p></section>`; }
async function vehicle(){ const d=await api('/vehicles/fiat-multipla'); app.innerHTML=`<h1>${d.vehicle.make} ${d.vehicle.model}</h1><div class="grid"><div class="card"><b>${d.stats.pages}</b><p>Imported pages</p></div><div class="card"><b>${d.stats.images}</b><p>Images</p></div><div class="card"><b>${d.stats.components}</b><p>Seeded components</p></div></div>`; }
async function search(){ app.innerHTML=`<h1>Search Multipla eLearn</h1><form id="f"><input id="q" placeholder="radiator fan, ABS, crank sensor" autofocus><button>Search</button></form><div id="results"></div>`; const run=async()=>{const q=document.getElementById('q').value; const d=await api('/search?q='+encodeURIComponent(q)); document.getElementById('results').innerHTML=(d.hits||[]).map(pageCard).join('')||'<p class="muted">No results.</p>';}; document.getElementById('f').onsubmit=e=>{e.preventDefault();run()}; run(); }
async function elearn(id){ const d=await api('/elearn/'+id); const p=d.page; app.innerHTML=`<article class="card"><h1>${esc(p.title)}</h1><p class="muted">${esc(p.breadcrumb||'')}</p><p><a target="_blank" href="${esc(p.source_url)}">Original source URL</a></p><h2>Images</h2>${d.images.map(i=>`<img class="thumb" src="${i.local_path?'/'+i.local_path:esc(i.image_url)}" alt="${esc(i.alt_text)}">`).join('')||'<p class="muted">No images captured.</p>'}<h2>Content</h2><p>${esc(p.content_text||'')}</p></article>`; }
async function components(){ const rows=await api('/components'); app.innerHTML=`<h1>Components</h1><div class="grid">${rows.map(c=>`<a class="card" href="/components/${c.slug}"><h3>${esc(c.name)}</h3><p class="muted">${c.related_pages} related pages</p>${(c.aliases||[]).map(a=>`<span class="pill">${esc(a)}</span>`).join('')}</a>`).join('')}</div>`; }
async function component(slug){ const d=await api('/components/'+slug), c=d.component; app.innerHTML=`<h1>${esc(c.name)}</h1><section class="card"><h2>Aliases</h2>${d.aliases.map(a=>`<span class="pill">${esc(a.alias)}</span>`).join('')}<h2>Future knowledge graph areas</h2><ul class="placeholders"><li>Parts: placeholder</li><li>Wiring: placeholder</li><li>Fault codes: placeholder</li><li>Diagnostics: placeholder</li><li>CAD models: placeholder</li></ul></section><h2>Related eLearn pages</h2>${d.pages.map(p=>pageCard(p)+((p.images||[]).slice(0,3).map(i=>`<img class="thumb" src="${i.local_path?'/'+i.local_path:esc(i.image_url)}">`).join(''))).join('')||'<p class="muted">Run the crawler and matching job to populate related pages.</p>'}`; }
async function route(){ try{ const path=location.pathname; if(path==='/') return home(); if(path==='/vehicles/fiat-multipla') return vehicle(); if(path==='/search') return search(); if(path.startsWith('/elearn/')) return elearn(path.split('/').pop()); if(path==='/components') return components(); if(path.startsWith('/components/')) return component(path.split('/').pop()); app.innerHTML='<h1>Not found</h1>'; }catch(e){app.innerHTML=`<div class="card"><h1>Error</h1><p>${esc(e.message)}</p></div>`} }
route();
